### ISSUE TITLE
ember-cli-version-checker dependency

### ISSUE THREAD

**Issue by buschtoens** [hhff/ember-infinity#16]
Seems like the `ember-cli-version-checker` dependency has to go to `"dependencies"` and not `"devDependencies"`.

```
$ ember version
version: 0.2.5
node: 2.0.2
npm: 2.10.0
```

Running an `ember` command crashes with this error.
```
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/jan/code/veltro/veltro/node_modules/ember-infinity/index.js:4:15)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Function.Addon.lookup (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/addon.js:665:19)
  at /home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/addons-factory.js:47:36
  at visit (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
  at DAG.topsort (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
  at AddonsFactory.initializeAddons (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
  at Project.initializeAddons (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/project.js:329:36)
  at Project.eachAddonCommand (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/project.js:380:10)
  at module.exports (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/cli/lookup-command.js:46:13)
  at CLI.<anonymous> (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/cli/cli.js:32:26)
  at lib$rsvp$$internal$$tryCatch (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

**Comment by buschtoens** [comment]
Hot fix: `npm i --save-dev ember-cli-version-checker`

**Comment by hhff** [comment]
thank @buschtoens - good call.  fixing now

**Comment by hhff** [comment]
fixed and released :+1:

**Comment by buschtoens** [comment]
Awesome :beers:
