### ISSUE TITLE
Tests Failing on Master

### ISSUE THREAD

**Issue by jherdman** [hhff/ember-infinity#184]
I cloned the repo today, and I'm seeing tests fail out of the box:

```
component:infinity-loader: it throws error when scrollable element is not found
    ✘ Should raise error

component:infinity-loader: it throws error when multiple scrollable elements are found
    ✘ Should raise error

component:infinity-loader: it throws error when scrollable is something other than nothing or string
    ✘ Promise rejected after it throws error when scrollable is something other than nothing or string: Cannot read property 'off' of undefined

    ✘ Expected 1 assertions, but 2 were run

component:infinity-loader: it checks if in view on the scroll event
    ✘ Promise rejected before it checks if in view on the scroll event: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application

    ✘ Died on test #2     at testWrapper (http://localhost:7357/assets/test-support.js:6236:11)
        at test (http://localhost:7357/assets/test-support.js:6250:39)
        at Module.callback (http://localhost:7357/assets/tests.js:825:24)
        at Module.exports (http://localhost:7357/assets/vendor.js:65:34)
        at Module.build (http://localhost:7357/assets/vendor.js:115:10)
        at findModule (http://localhost:7357/assets/vendor.js:163:9)
        at requireModule (http://localhost:7357/assets/vendor.js:150:12): this.subject is not a function

    ✘ Expected 1 assertions, but 2 were run

component:infinity-loader: it checks if in view on the resize event
    ✘ Assertion after the final `assert.async` was resolved

    ✘ Expected 1 assertions, but 2 were run
```

**Comment by snewcomer** [comment]
master is passing again.
