### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by temo44** [hhff/ember-infinity#3]
When trying to execute the command

ember install:addon ember-infinity

I get the following message:

Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at D:\projects\projectTest\brighter-ember\node_modules\ember-cli\lib\models\project.js:459:53
    at find (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\node_modules\lodash-node\modern\collections\find.js:64:11)
    at Project.findAddonByName (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\lib\models\project.js:458:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\lib\tasks\addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (D:\projects\projectTest\
brighter-ember\node_modules\ember-cli\lib\tasks\addon-install.js:52:30)
    at Class.<anonymous> (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\lib\tasks\addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:472:11)
    at lib$rsvp$asap$$flush (D:\projects\projectTest\brighter-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1290:9)

Thus I cannot install the addon

**Comment by hhff** [comment]
Weird!  I just created a fresh Ember app and installed it fine.

What version of Ember CLI are you on?

**Comment by temo44** [comment]
ow damn. I haven't tried on a fresh install. I'm on Ember server 0.2.1. I'll try it on a fresh one too tomorrow

**Comment by temo44** [comment]
@hhff I've tried to add the addon on a fresh install. Everything works as intended.

**Comment by hhff** [comment]
Awesome!
